/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scholastica;

import java.sql.*;
import java.util.*;
import javax.swing.*;


/**
 *
 * @author x7000328
 */
public class CreationEnfantSimp extends javax.swing.JFrame {
   int idEnfant, idNvEnfant;
   String idFenetre = "CreationEnfantSimp";
    
    /**
     * Creates new form CrEnfantSimp
     */
    public CreationEnfantSimp(int _idEnfant) {
        initComponents();
        idEnfant = _idEnfant;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labNom = new javax.swing.JLabel();
        labPrenom = new javax.swing.JLabel();
        labDtNaissance = new javax.swing.JLabel();
        tfNom = new javax.swing.JTextField();
        tfPrenom = new javax.swing.JTextField();
        butValider = new javax.swing.JButton();
        butAnnuler = new javax.swing.JButton();
        ftfDtNaissance = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Création d'enfant simplifiée");

        labNom.setText("* Nom");

        labPrenom.setText("* Prénom");

        labDtNaissance.setText("* Date de naissance");

        tfNom.setToolTipText("");

        butValider.setText("Valider");
        butValider.setActionCommand("");
        butValider.setAutoscrolls(true);
        butValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butValiderActionPerformed(evt);
            }
        });

        butAnnuler.setText("Annuler");
        butAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnulerActionPerformed(evt);
            }
        });

        ftfDtNaissance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        ftfDtNaissance.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labDtNaissance)
                                    .addComponent(labPrenom)
                                    .addComponent(labNom))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ftfDtNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butValider)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butAnnuler)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNom)
                    .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labPrenom)
                    .addComponent(tfPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labDtNaissance)
                    .addComponent(ftfDtNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butValider)
                    .addComponent(butAnnuler))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butValiderActionPerformed
        // récupérer les infos des champs
        // si 1 champ = null, fenêtre d'erreur
        // sinon création de l'objet Enfant
        // puis enregistrement dans la base
        String nom = tfNom.getText();
        String prenom = tfPrenom.getText();
        java.util.Date dtNaissance = (java.util.Date)ftfDtNaissance.getValue();
        java.sql.Date sqlDtNaissance = null;
        if (null != dtNaissance) { sqlDtNaissance = new java.sql.Date(dtNaissance.getTime()); }

        if (nom.equals("") || prenom.equals("") || dtNaissance.equals("")) {
            JOptionPane.showMessageDialog(null, "Il faut remplir tous les champs.", "Erreur !", JOptionPane.ERROR_MESSAGE);
        } else {
            Base b = new Base();
            Connection conn = null;
            PreparedStatement ps;
            ResultSet res;
            b.connexionBD();
            conn = b.getConnect();
            String sql1 = "insert into p1514568.Enfant (nom_enfant, prenom_enfant, date_naissance) values (?, ?, ?)";
            String sql2 = "select max(id_enfant) as maxid from p1514568.Enfant where nom_enfant = ? and prenom_enfant = ? and date_naissance = ?";
            String sql3 = "insert into p1514568.Fratrie (id_enfant1, id_enfant2) values (?, ?)";
            
            try {
                ps = conn.prepareStatement(sql1);
                ps.setString(1, nom);
                ps.setString(2, prenom);
                ps.setDate(3, sqlDtNaissance);
                ps.executeUpdate();
                
                ps = conn.prepareStatement(sql2);
                ps.setString(1, nom);
                ps.setString(2, prenom);
                ps.setDate(3, sqlDtNaissance);
                res = ps.executeQuery();
                while (res.next()) {
                    idNvEnfant = res.getInt("maxid");
                }
                
                ps = conn.prepareStatement(sql3);
                ps.setInt(1, idEnfant);
                ps.setInt(2, idNvEnfant);
                ps.executeUpdate();                

                res.close();
                ps.close();
                
                CreationEleve w = new CreationEleve(idEnfant);
                w.setVisible(true); 
                w.setLocationRelativeTo(null);
                dispose();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }  
        }
    }//GEN-LAST:event_butValiderActionPerformed

    private void butAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnulerActionPerformed
        CreationEleve w = new CreationEleve(idEnfant);
        w.setVisible(true); 
        w.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_butAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CrEnfantSimp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CrEnfantSimp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CrEnfantSimp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CrEnfantSimp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CrEnfantSimp().setVisible(true);
//            }
//        });
//    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAnnuler;
    private javax.swing.JButton butValider;
    private javax.swing.JFormattedTextField ftfDtNaissance;
    private javax.swing.JLabel labDtNaissance;
    private javax.swing.JLabel labNom;
    private javax.swing.JLabel labPrenom;
    private javax.swing.JTextField tfNom;
    private javax.swing.JTextField tfPrenom;
    // End of variables declaration//GEN-END:variables
}
