/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scholastica;

import java.sql.*;

/**
 *
 * @author Emanuelle
 */
public class CreationAffectation extends javax.swing.JFrame {

    String idFenetre = "CreationAffectation";
    String idFenetrePrec;
    int idClasse, idAdulte;
    
    /**
     * Creates new form CreationAffectation
     */
    public CreationAffectation() {
        initComponents();
    }
    
    public CreationAffectation(String _idFenetrePrec, int _idClasse, int _idAdulte) {
        idFenetrePrec = _idFenetrePrec;
        idClasse = _idClasse;
        idAdulte = _idAdulte;
        String label = "Confirmez-vous que ";
        initComponents();
        
        Base b = new Base();
        Connection conn;
        PreparedStatement stmt;
        ResultSet res;
        b.connexionBD();
        conn = b.getConnect();
        
        try {
            stmt = conn.prepareStatement("select nom_adulte, prenom_adulte from p1514568.Adulte where id_adulte = ?");
            stmt.setInt(1, idAdulte);
            res = stmt.executeQuery();
            
            while (res.next()){     
                label += res.getString("prenom_adulte") + " " + res.getString("nom_adulte");
            }
            
            label += " est affecté·e à la classe « ";

            stmt = conn.prepareStatement("select nom_classe from p1514568.Classe where id_classe = ?");
            stmt.setInt(1, idClasse);
            res = stmt.executeQuery();
            
            while (res.next()){     
                label += res.getString("nom_classe");
            }

            label += " » ?";
            
            panResult.setText(label);
            
            res.close();
            stmt.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butValider = new javax.swing.JButton();
        butAnnuler = new javax.swing.JButton();
        labNiveau = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panResult = new javax.swing.JTextPane();
        cbTitulaire = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        taCommentaire = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Affectation d'un enseignant à une classe");

        butValider.setText("Valider");
        butValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butValiderActionPerformed(evt);
            }
        });

        butAnnuler.setText("Annuler");
        butAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnulerActionPerformed(evt);
            }
        });

        labNiveau.setText("Commentaire");

        jScrollPane2.setBorder(null);

        panResult.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        panResult.setBorder(null);
        jScrollPane2.setViewportView(panResult);

        cbTitulaire.setText("Titulaire");

        taCommentaire.setColumns(20);
        taCommentaire.setRows(5);
        jScrollPane1.setViewportView(taCommentaire);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labNiveau)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butValider)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butAnnuler)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbTitulaire)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(labNiveau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbTitulaire)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butValider)
                    .addComponent(butAnnuler))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butValiderActionPerformed
        Base b = new Base();
        Connection conn;
        PreparedStatement stmt;
        b.connexionBD();
        conn = b.getConnect();        

        try {
            stmt = conn.prepareStatement("insert into p1514568.Affectation (id_adulte, id_classe, commentaire, titulaire) values (?, ?, ?, ?)");
            stmt.setInt(1, idAdulte);
            stmt.setInt(2, idClasse);
            stmt.setString(3, taCommentaire.getText());
            stmt.setBoolean(4, cbTitulaire.isSelected());
            stmt.executeUpdate();
            stmt.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    
        CreationClasse f = new CreationClasse(idFenetre, idClasse);
        f.setVisible(true); 
        f.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_butValiderActionPerformed

    private void butAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnulerActionPerformed
        RechercheAdulte f = new RechercheAdulte("CreationClasse", idClasse);
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_butAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreationAffectation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreationAffectation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreationAffectation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreationAffectation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreationAffectation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAnnuler;
    private javax.swing.JButton butValider;
    private javax.swing.JCheckBox cbTitulaire;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labNiveau;
    private javax.swing.JTextPane panResult;
    private javax.swing.JTextArea taCommentaire;
    // End of variables declaration//GEN-END:variables
}
