/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scholastica;

import java.sql.*;

/**
 *
 * @author Emanuelle
 */
public class CreationResponsabilite extends javax.swing.JFrame {

    String idFenetre = "CreationResponsabilite";
    int idEnfant, idAdulte;
    
    /**
     * Creates new form CreationAffectation
     */
    public CreationResponsabilite() {
        initComponents();
    }
    
    public CreationResponsabilite(int _idEnfant, int _idAdulte) {
        idEnfant = _idEnfant;
        idAdulte = _idAdulte;
        String label = "Confirmez-vous que ";
        initComponents();
        
        Base b = new Base();
        Connection conn;
        PreparedStatement stmt;
        ResultSet res;
        b.connexionBD();
        conn = b.getConnect();
        
        try {
            stmt = conn.prepareStatement("select nom_adulte, prenom_adulte from p1514568.Adulte where id_adulte = ?");
            stmt.setInt(1, idAdulte);
            res = stmt.executeQuery();
            
            while (res.next()){     
                label += res.getString("prenom_adulte") + " " + res.getString("nom_adulte");
            }
            
            label += " est responsable de l'enfant ";

            stmt = conn.prepareStatement("select nom_enfant, prenom_enfant from p1514568.Enfant where id_enfant = ?");
            stmt.setInt(1, idEnfant);
            res = stmt.executeQuery();
            
            while (res.next()){     
                label += res.getString("prenom_enfant") + " " + res.getString("nom_enfant");
            }

            label += " ?";
            
            panResult.setText(label);
            
            res.close();
            stmt.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butValider = new javax.swing.JButton();
        butAnnuler = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        panResult = new javax.swing.JTextPane();
        cbAutorisation = new javax.swing.JCheckBox();
        cbLien = new javax.swing.JComboBox<>();
        labLien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Création d'un lien familial");

        butValider.setText("Valider");
        butValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butValiderActionPerformed(evt);
            }
        });

        butAnnuler.setText("Annuler");
        butAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnulerActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(null);

        panResult.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        panResult.setBorder(null);
        jScrollPane2.setViewportView(panResult);

        cbAutorisation.setSelected(true);
        cbAutorisation.setText("Autorisation de retirer l'enfant");

        cbLien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parent", "Autre famille", "Autre" }));

        labLien.setText("Lien ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butValider)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                                .addComponent(butAnnuler))
                            .addComponent(jScrollPane2))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbAutorisation)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labLien)
                        .addGap(18, 18, 18)
                        .addComponent(cbLien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labLien)
                    .addComponent(cbLien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(cbAutorisation)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butValider)
                    .addComponent(butAnnuler))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butValiderActionPerformed
        Base b = new Base();
        Connection conn;
        PreparedStatement stmt;
        b.connexionBD();
        conn = b.getConnect();        

        try {
            stmt = conn.prepareStatement("insert into p1514568.Responsabilite (id_enfant, id_adulte, lien, autoriser) values (?, ?, ?, ?)");
            stmt.setInt(1, idEnfant);
            stmt.setInt(2, idAdulte);
            stmt.setString(3, cbLien.getSelectedItem().toString());
            stmt.setBoolean(4, cbAutorisation.isSelected());
            System.out.println(stmt);
            stmt.executeUpdate();
            stmt.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    
        CreationEleve f = new CreationEleve(idEnfant);
        f.setVisible(true); 
        dispose();
    }//GEN-LAST:event_butValiderActionPerformed

    private void butAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnulerActionPerformed
        RechercheAdulte f = new RechercheAdulte("CreationEleve", idEnfant);
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_butAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreationResponsabilite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreationResponsabilite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreationResponsabilite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreationResponsabilite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreationResponsabilite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAnnuler;
    private javax.swing.JButton butValider;
    private javax.swing.JCheckBox cbAutorisation;
    private javax.swing.JComboBox<String> cbLien;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labLien;
    private javax.swing.JTextPane panResult;
    // End of variables declaration//GEN-END:variables
}
