/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scholastica;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author p1514568
 */
public class Creation_eleve extends javax.swing.JFrame {

    int idEnfant;
    String idFenetre = "creationEnfant";

    /**
     * Creates new form Crea_eleve
     */
    public Creation_eleve() {
        initComponents();
        idEnfant = -1;
       
    }

    public Creation_eleve(int _idEnfant) {
        initComponents();
        idEnfant = _idEnfant;
        this.populate(idEnfant);
    }

    public void populate(int idEnfant) {
        Base b = new Base();
        Connection conn = null;
        ResultSet res;
        PreparedStatement statement;
        b.connexionBD();
        conn = b.getConnect();

        try {
            statement = conn.prepareStatement("select * from p1514568.Enfant where id_enfant = ?");
            statement.setInt(1, idEnfant);
            res = statement.executeQuery();

            while (res.next()) {

                //String date_inscri_eleve = ch_date_inscri_eleve.getText();
                //String date_radiation_eleve = ch_date_radiation_eleve.getText();
                String nom_eleve = res.getString("nom_enfant");
                String prenom_enfant = res.getString("prenom_enfant");
                String date_naissance_eleve = res.getString("date_naissance");
                String lieu_naissance_eleve = res.getString("ville_naissance");
                String nationalite_eleve = res.getString("nationalite");
                String adresse_eleve = res.getString("adresse_enfant");
                String telephone_eleve = res.getString("tel_enfant");
                String situ_famille_eleve = res.getString("situation_familiale");
                String tel_secu = res.getString("tel_secu_social");
                String adr_secu = res.getString("adr_secu_social");
                String tel_assu = res.getString("tel_assurance");
                String adr_assu = res.getString("adr_assurance");
                String nom_medecin = res.getString("nom_medecin");
                String tel_medecin = res.getString("tel_medecin");
                String adr_medecin = res.getString("adr_medecin");
                String info_medical = res.getString("infos_medicales");
                String date_rapel_antitenaq = res.getString("date_vaccin");
                Boolean lunette_eleve = res.getBoolean("port_lunettes");
                Boolean pai_eleve = res.getBoolean("pai");
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                String sDateDebut = null;
                String sDateFin = null;
                Date dateDebut = res.getDate("date_inscription");
                if (null != dateDebut) {
                    sDateDebut = formatter.format(dateDebut);
                }
                Date dateFin = res.getDate("date_radiation");
                if (null != dateFin) {
                    sDateFin = formatter.format(dateFin);
                }

                res.close();
                statement.close();

                ch_nom_eleve.setText(nom_eleve);
                ch_prenom_enfant.setText(prenom_enfant);
                ch_naissance_eleve.setText(date_naissance_eleve);
                ch_lieu_naiss_eleve.setText(lieu_naissance_eleve);
                ch_nationalite_eleve.setText(nationalite_eleve);
                ch_adresse_eleve.setText(adresse_eleve);
                ch_tel_eleve.setText(telephone_eleve);
                ch_situ_famil_eleve.setText(situ_famille_eleve);
                ch_tel_secu.setText(tel_secu);
                ch_adr_secu.setText(adr_secu);
                ch_tel_assu.setText(tel_assu);
                ch_adr_assu.setText(adr_assu);
                ch_nom_medecin.setText(nom_medecin);
                ch_tel_medecin.setText(tel_medecin);
                ch_adr_medecin.setText(adr_medecin);
                ch_info_medical.setText(info_medical);
                ch_date_rapel_antitenaq.setText(date_rapel_antitenaq);
                ch_lunette_eleve.setSelected(lunette_eleve);
                ch_pai_eleve.setSelected(pai_eleve);
                ch_date_inscri_eleve.setText(sDateDebut);
                ch_date_radiation_eleve.setText(sDateFin);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ch_nom_eleve = new javax.swing.JTextField();
        ch_prenom_enfant = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ch_lieu_naiss_eleve = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ch_nationalite_eleve = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ch_adresse_eleve = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        ch_tel_eleve = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ch_lunette_eleve = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        ch_situ_famil_eleve = new javax.swing.JTextArea();
        valider = new javax.swing.JButton();
        ret_acc_crea_ele = new javax.swing.JButton();
        ch_naissance_eleve = new javax.swing.JFormattedTextField();
        ch_date_inscri_eleve = new javax.swing.JFormattedTextField();
        ch_date_radiation_eleve = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        rech_crea_ele = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ch_tel_secu = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ch_adr_secu = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ch_tel_assu = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ch_adr_assu = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        ch_nom_medecin = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ch_tel_medecin = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ch_adr_medecin = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        ch_info_medical = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ch_notif_evs = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        ch_notif_avs = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        ch_rased_maitree = new javax.swing.JCheckBox();
        ch_rased_maitreg = new javax.swing.JCheckBox();
        ch_rased_psy = new javax.swing.JCheckBox();
        ch_rased_assi_social = new javax.swing.JCheckBox();
        ch_rased_mdph = new javax.swing.JCheckBox();
        ch_date_rapel_antitenaq = new javax.swing.JFormattedTextField();
        ch_pai_eleve = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nom");

        ch_nom_eleve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_nom_eleveActionPerformed(evt);
            }
        });

        ch_prenom_enfant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_prenom_enfantActionPerformed(evt);
            }
        });

        jLabel3.setText("Prénom");

        jLabel4.setText("Date de naissance");

        ch_lieu_naiss_eleve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_lieu_naiss_eleveActionPerformed(evt);
            }
        });

        jLabel5.setText("Lieu de naissance");

        jLabel6.setText("Nationalité");

        jLabel7.setText("Date d'inscription");

        jLabel8.setText("Date de radiation");

        jLabel9.setText("Adresse");

        ch_adresse_eleve.setColumns(20);
        ch_adresse_eleve.setRows(5);
        jScrollPane1.setViewportView(ch_adresse_eleve);

        jLabel10.setText("Téléphone");

        ch_tel_eleve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_tel_eleveActionPerformed(evt);
            }
        });

        jLabel11.setText("Port de lunettes");

        ch_lunette_eleve.setText("ch_lunette_eleve");
        this.setLocationRelativeTo(null);
        ch_lunette_eleve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_lunette_eleveActionPerformed(evt);
            }
        });

        jLabel12.setText("Situation familiale");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        ch_situ_famil_eleve.setColumns(20);
        ch_situ_famil_eleve.setRows(5);
        jScrollPane9.setViewportView(ch_situ_famil_eleve);

        valider.setText("Créer élève");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        ret_acc_crea_ele.setText("Accueil");
        ret_acc_crea_ele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ret_acc_crea_eleActionPerformed(evt);
            }
        });

        jButton1.setText("Créer");

        rech_crea_ele.setText("Rechercher");
        rech_crea_ele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rech_crea_eleActionPerformed(evt);
            }
        });

        jButton4.setText("Créer");

        jButton5.setText("Rechercher");

        jButton2.setText("Annuler");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ch_nom_eleve, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ch_prenom_enfant, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ch_nationalite_eleve, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ch_tel_eleve, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ch_lunette_eleve))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ch_naissance_eleve))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ch_lieu_naiss_eleve, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ch_date_inscri_eleve)
                                        .addComponent(ch_date_radiation_eleve)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rech_crea_ele))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(valider)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(ret_acc_crea_ele)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ch_nom_eleve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ch_prenom_enfant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ch_naissance_eleve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ch_lieu_naiss_eleve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ch_nationalite_eleve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ch_date_inscri_eleve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ch_date_radiation_eleve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ch_tel_eleve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(ch_lunette_eleve))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(rech_crea_ele))
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valider)
                    .addComponent(jButton2)
                    .addComponent(ret_acc_crea_ele))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fiche élève", jPanel1);

        jLabel1.setText("Centre de sécurité sociale");

        jLabel13.setText("Téléphone");

        jLabel14.setText("Adresse");

        ch_adr_secu.setColumns(20);
        ch_adr_secu.setRows(5);
        jScrollPane4.setViewportView(ch_adr_secu);

        jLabel15.setText("Assurance scolaire");

        jLabel16.setText("Téléphone");

        jLabel17.setText("Adresse");

        ch_adr_assu.setColumns(20);
        ch_adr_assu.setRows(5);
        jScrollPane5.setViewportView(ch_adr_assu);

        jLabel18.setText("Nom medecin");

        jLabel19.setText("Téléphone");

        jLabel20.setText("Adresse");

        ch_adr_medecin.setColumns(20);
        ch_adr_medecin.setRows(5);
        jScrollPane6.setViewportView(ch_adr_medecin);

        jLabel21.setText("Informations médicales");

        ch_info_medical.setColumns(20);
        ch_info_medical.setRows(5);
        jScrollPane7.setViewportView(ch_info_medical);

        jLabel22.setText("Dernier rappel antiténanique");

        jLabel23.setText("Informations pédagogiques");

        jLabel24.setText("PAI");

        jLabel25.setText("Notification EVS");

        ch_notif_evs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3h", "6h", "9h", "12h" }));
        ch_notif_evs.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ch_notif_evsItemStateChanged(evt);
            }
        });
        ch_notif_evs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_notif_evsActionPerformed(evt);
            }
        });

        jLabel26.setText("Notification AVS");

        ch_notif_avs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3h", "6h", "9h", "12h" }));

        jLabel27.setText("RASED");

        ch_rased_maitree.setText("Maître E");

        ch_rased_maitreg.setText("Maître G");

        ch_rased_psy.setText("Psychologue");

        ch_rased_assi_social.setText("Assistante sociale");

        ch_rased_mdph.setText("Suivi MDPH");
        ch_rased_mdph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_rased_mdphActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ch_tel_secu, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ch_tel_assu, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ch_tel_medecin))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ch_nom_medecin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(26, 26, 26)
                                .addComponent(ch_date_rapel_antitenaq, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel21)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ch_pai_eleve))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ch_notif_evs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ch_notif_avs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(ch_rased_psy)
                                        .addGap(18, 18, 18)
                                        .addComponent(ch_rased_mdph))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(ch_rased_maitree)
                                        .addGap(18, 18, 18)
                                        .addComponent(ch_rased_maitreg))
                                    .addComponent(ch_rased_assi_social))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(ch_tel_secu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel15))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ch_tel_assu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(ch_date_rapel_antitenaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(ch_nom_medecin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(ch_tel_medecin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(ch_pai_eleve))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(ch_notif_evs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(ch_notif_avs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(ch_rased_maitree)
                            .addComponent(ch_rased_maitreg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ch_rased_psy)
                            .addComponent(ch_rased_mdph))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ch_rased_assi_social)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Informations médicales et pédagogiques", jPanel2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Historique", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ch_nom_eleveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_nom_eleveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch_nom_eleveActionPerformed

    private void ch_tel_eleveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_tel_eleveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch_tel_eleveActionPerformed

    private void ch_lunette_eleveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_lunette_eleveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch_lunette_eleveActionPerformed

    private void ch_prenom_enfantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_prenom_enfantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch_prenom_enfantActionPerformed

    private void ch_lieu_naiss_eleveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_lieu_naiss_eleveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch_lieu_naiss_eleveActionPerformed

    private void ch_rased_mdphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_rased_mdphActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch_rased_mdphActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        // TODO add your handling code here:
        String nom_enfant = ch_nom_eleve.getText();
        String prenom_enfant = ch_prenom_enfant.getText();
        
        String lieu_naiss_eleve = ch_lieu_naiss_eleve.getText();
        String nation_eleve = ch_nationalite_eleve.getText();
        java.util.Date DateNaissance = (Date) ch_naissance_eleve.getValue();                 
        java.sql.Date sqlDateNaissance = null;
        if (null != DateNaissance) 
		{
            sqlDateNaissance = new java.sql.Date(DateNaissance.getTime());
        }
        String adresse_eleve = ch_adresse_eleve.getText();
        String tel_eleve = ch_tel_eleve.getText();
        String sit_famille_eleve = ch_situ_famil_eleve.getText();
        String tel_secu = ch_tel_secu.getText();
        String adr_secu = ch_adr_secu.getText();
        String tel_assu = ch_tel_assu.getText();
        String adr_assu = ch_adr_assu.getText();
        String nom_medecin = ch_nom_medecin.getText();
        String tel_medecin = ch_tel_medecin.getText();
        String adr_medecin = ch_adr_medecin.getText();
        String info_medical = ch_info_medical.getText();
        java.util.Date DateVaccin = (Date) ch_date_rapel_antitenaq.getValue();                 
        java.sql.Date sqlDateVaccin = null;
        if (null != DateVaccin) 
		{
            sqlDateVaccin = new java.sql.Date(DateVaccin.getTime());
        }
        java.util.Date DateDebut = (Date) ch_date_inscri_eleve.getValue();                 
        java.sql.Date sqlDateDebut = null;
        if (null != DateDebut) 
		{
            sqlDateDebut = new java.sql.Date(DateDebut.getTime());
        }
        java.util.Date DateFin = (Date) ch_date_radiation_eleve.getValue();
        java.sql.Date sqlDateFin = null;
        if (null != DateFin) 
		{
            sqlDateFin = new java.sql.Date(DateFin.getTime());
        }

        if (nom_enfant.equals("") || prenom_enfant.equals("")) 
			{
				JOptionPane.showMessageDialog(null, "Il faut remplir au moins les champs Nom et Prénom.", "Erreur !", JOptionPane.ERROR_MESSAGE);
			} 
		else
			{
				Base b = new Base();
				Connection conn = null;
				PreparedStatement statement;
				b.connexionBD();
				conn = b.getConnect();
				String sql = "";

            if (idEnfant < 0) 
				{
					sql = "insert into p1514568.Enfant "
                        + "(nom_enfant, prenom_enfant, date_naissance, ville_naissance, nationalite, adresse_enfant, tel_enfant, situation_familiale, tel_secu_social, adr_secu_social, tel_assurance, adr_assurance, nom_medecin, tel_medecin, adr_medecin, infos_medicales, date_vaccin, port_lunettes, pai,  date_inscription, date_radiation ) values "
                        + "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? , ?, ?, ?, ?, ?, ?, ?)";
				} 
			else 
				{
					sql = "update p1514568.Enfant "
                        + "set nom_enfant = ?"
                        + ", prenom_enfant = ?"
                        + ", date_naissance = ?"
                        + ", ville_naissance = ?"
                        + ", nationalite = ?"
                        + ", adresse_enfant = ?"
                        + ", tel_enfant = ?"
                        + ", situation_familiale = ?"
                        + ", tel_secu_social = ?"
                        + ", adr_secu_social = ?"
                        + ", tel_assurance = ?"
                        + ", adr_assurance = ?"
                        + ", nom_medecin = ?"
                        + ", tel_medecin = ?"
                        + ", adr_medecin = ?"
                        + ", infos_medicales = ?"
                        + ", date_vaccin = ?"
                        + ", port_lunettes = ?"
                        + ", pai = ?"
                        + ", date_inscription = ?"
                        + ", date_radiation = ?"
                        + " where id_enfant = " + idEnfant;
				}
            System.out.println(sql);
            try 
			{
                statement = conn.prepareStatement(sql);
                statement.setString(1, nom_enfant);
                statement.setString(2, prenom_enfant);
                statement.setDate(3, sqlDateNaissance);
                statement.setString(4, lieu_naiss_eleve);
                statement.setString(5, nation_eleve);
                statement.setString(6, adresse_eleve);
                statement.setString(7, tel_eleve);
                statement.setString(8, sit_famille_eleve);
                statement.setString(9, tel_secu);
                statement.setString(10, adr_secu);
                statement.setString(11, tel_assu);
                statement.setString(12, adr_assu);
                statement.setString(13, nom_medecin);
                statement.setString(14, tel_medecin);
                statement.setString(15, adr_medecin);
                statement.setString(16, info_medical);
                statement.setDate(17, sqlDateVaccin);
                statement.setBoolean(18, ch_lunette_eleve.isSelected());
                statement.setBoolean(19, ch_pai_eleve.isSelected());
                statement.setDate(20, sqlDateDebut);
                statement.setDate(21, sqlDateFin);

                statement.executeUpdate();
                statement.close();

                /*Recherche_Adulte w = new Recherche_Adulte();
                w.setVisible(true);
                dispose();*/

			} catch (SQLException e) 
				{
					System.out.println(e.getMessage());
				}
        }
    }//GEN-LAST:event_validerActionPerformed

    private void ret_acc_crea_eleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ret_acc_crea_eleActionPerformed
        // TODO add your handling code here:
        Accueil acc = new Accueil();
        acc.setVisible(true);
        acc.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_ret_acc_crea_eleActionPerformed

    private void rech_crea_eleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rech_crea_eleActionPerformed
        // TODO add your handling code here:
        /*Recherche_Adulte rech_adu = new Recherche_Adulte();
        rech_adu.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_rech_crea_eleActionPerformed

    private void ch_notif_evsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_notif_evsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ch_notif_evsActionPerformed

    private void ch_notif_evsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ch_notif_evsItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_ch_notif_evsItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                





}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creation_eleve.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        





} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creation_eleve.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        





} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creation_eleve.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        





} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creation_eleve.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creation_eleve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ch_adr_assu;
    private javax.swing.JTextArea ch_adr_medecin;
    private javax.swing.JTextArea ch_adr_secu;
    private javax.swing.JTextArea ch_adresse_eleve;
    private javax.swing.JFormattedTextField ch_date_inscri_eleve;
    private javax.swing.JFormattedTextField ch_date_radiation_eleve;
    private javax.swing.JFormattedTextField ch_date_rapel_antitenaq;
    private javax.swing.JTextArea ch_info_medical;
    private javax.swing.JTextField ch_lieu_naiss_eleve;
    private javax.swing.JCheckBox ch_lunette_eleve;
    private javax.swing.JFormattedTextField ch_naissance_eleve;
    private javax.swing.JTextField ch_nationalite_eleve;
    private javax.swing.JTextField ch_nom_eleve;
    private javax.swing.JTextField ch_nom_medecin;
    private javax.swing.JComboBox<String> ch_notif_avs;
    private javax.swing.JComboBox<String> ch_notif_evs;
    private javax.swing.JCheckBox ch_pai_eleve;
    private javax.swing.JTextField ch_prenom_enfant;
    private javax.swing.JCheckBox ch_rased_assi_social;
    private javax.swing.JCheckBox ch_rased_maitree;
    private javax.swing.JCheckBox ch_rased_maitreg;
    private javax.swing.JCheckBox ch_rased_mdph;
    private javax.swing.JCheckBox ch_rased_psy;
    private javax.swing.JTextArea ch_situ_famil_eleve;
    private javax.swing.JTextField ch_tel_assu;
    private javax.swing.JTextField ch_tel_eleve;
    private javax.swing.JTextField ch_tel_medecin;
    private javax.swing.JTextField ch_tel_secu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton rech_crea_ele;
    private javax.swing.JButton ret_acc_crea_ele;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
